// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Repository;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20230613172811_InsertInformationDb")]
    partial class InsertInformationDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Application.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Handmade Metal Chips"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Intelligent Rubber Hat"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Handmade Concrete Bacon"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Handcrafted Concrete Hat"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Incredible Wooden Sausages"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Refined Frozen Towels"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Practical Soft Chips"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Handcrafted Cotton Ball"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Small Metal Pizza"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Ergonomic Soft Bacon"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Intelligent Frozen Tuna"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Generic Plastic Computer"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Sleek Steel Pants"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Licensed Concrete Computer"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Handcrafted Concrete Shirt"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Incredible Granite Hat"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Handmade Metal Car"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Small Cotton Shirt"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Intelligent Steel Tuna"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Practical Metal Gloves"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
